FORK := fork_demo.c
ARGV = argv_demo.c
FILE = open_file.c
REPLACE = replace.c

fork:
	@gcc -o fork-demo $(FORK)
	@echo "Finished compiling $(FORK)"

argv:
	@gcc -o argv-demo $(ARGV)
	@echo "Finished compiling $(ARGV)"

file:
	@gcc -o file-demo $(FILE)
	@echo "Finished compiling $(FILE)"


replace:
	@gcc -o replace-demo $(REPLACE)
	@echo "Finished compiling $(REPLACE)"